### ISSUE TITLE
The MajorStep info of HorizontalAxis not displayed on IOS

### ISSUE THREAD

**Issue by SimenCTan** [telerik/maui-samples#18]
### Android display detail
![image](https://user-images.githubusercontent.com/19427810/179485544-88262898-7710-452e-8141-fa96fd65af51.png)

### IOS 15.4 display detail
![image](https://user-images.githubusercontent.com/19427810/179486235-b5166966-2d42-4111-87fe-7afa321bb7bc.png)

**Comment by didiyordanova** [comment]
Hi @SimenCTan, 
I have requested additional information, but such wasn't provided from your side. 
I have closed this issue due to inactivity.
